drop table if exists CUSTOMER;

CREATE TABLE `CUSTOMER` (
    `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(255) DEFAULT NULL,
    `CONTACT` VARCHAR(255) DEFAULT NULL,
    `TELEPHONE` VARCHAR(255) DEFAULT NULL,
    `EMAIL` VARCHAR(255) DEFAULT NULL,
    `REMARK` TEXT,
    PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;
